project_id = "cnviokaxrrmgiaffrtgb"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-purchase-email]
verify_jwt = false

[functions.free-trial]
verify_jwt = false
